name: Build and upload to ghcr

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{github.actor}}
          password: ${{secrets.GITHUB_TOKEN}}
      - run:
          docker build -t ghcr.io/kruemmelspalter/kasm-concrete:latest .
          docker push ghcr.io/kruemmelspalter/kasm-concrete:latest
     